### ISSUE TITLE
FastSerial Issue

### ISSUE THREAD

**Issue by rglockenmeier** [alaney/arduino-mavlink#1]
The included FastSerial library does not work. If you attempt to run the example code, you end up with errors for conflicting types.

This is an issue that many Mavlink Arduino users seem to have run into. However, I have yet to find a fixed copy on the internet. Would be a very good issue to iron out.

**Comment by alaney** [comment]
That is interesting because I do not get any such error. Did you put the "libraries" folder in your Arduino sketchbook? This is a mistake I have made many times. As a side note, I had the same problem as you, not being able to find a working arduino/mavlink example. That is why I wrote this one. I would like to help you get it running

**Comment by alaney** [comment]
Ok, after a little bit of searching I remember getting this error at first. I had to change a line or two of code in FastSerial.h and FastSerial.cpp. They should be correct in the file you downloaded. Be sure that you don't have another copy of FastSerial in you libraries. Let me know if you still have problems

**Comment by rglockenmeier** [comment]
Well that fixed it. Thanks for the help! I'll let you know what else I run into.

**Comment by alaney** [comment]
Awesome!
