### ISSUE TITLE
Linker Errors

### ISSUE THREAD

**Issue by rglockenmeier** [alaney/arduino-mavlink#2]
I get the following compiler errors when trying to compile the included test program:

ArduinoMAVLink.cpp.o: In function `__vector_18':
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to`__FastSerial__rxBuffer'
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to `__FastSerial__rxBuffer'
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to`__FastSerial__rxBuffer'
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to `__FastSerial__rxBuffer'
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to`__FastSerial__rxBuffer'
ArduinoMAVLink.cpp.o:C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: more undefined references to `__FastSerial__rxBuffer' follow
ArduinoMAVLink.cpp.o: In function`__vector_19':
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to `__FastSerial__txBuffer'
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to`__FastSerial__txBuffer'
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to `__FastSerial__txBuffer'
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to`__FastSerial__txBuffer'
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to `__FastSerial__txBuffer'
ArduinoMAVLink.cpp.o:C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: more undefined references to`__FastSerial__txBuffer' follow
ArduinoMAVLink.cpp.o: In function `__static_initialization_and_destruction_0':
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:9: undefined reference to`FastSerial::FastSerial(unsigned char, unsigned char volatile_, unsigned char volatile_, unsigned char volatile_, unsigned char volatile_, unsigned char, unsigned char, unsigned char)'
ArduinoMAVLink.cpp.o: In function `setup':
C:\Users\gimlithepirate\Desktop\arduino-1.0.3/ArduinoMAVLink.ino:14: undefined reference to`FastSerial::begin(long)

It appears to be some kind of linker error. I am referencing the exact files in my includes instead (i.e. #include "C:/Arduino/libraries/FastSerial/FastSerial.h") instead of trusting the relative linking just to ensure I get the right file. Doesn't seem to be working seeing as something is not getting defined correctly.

Any thoughts as to the source of the problem?

**Comment by alaney** [comment]
I'm not certain, but I believe this is a result of the way #include works. When you do something like "#include <FastSerial.h>" this is not a "relative link" as you say. This is telling the arduino compiler to grab all the files in that library file, e.g. "FastSerial". If you give it the long path "C:/Arduino/libraries/FastSerial/FastSerial.h", you are telling the compiler to ONLY include the "FastSerial.h" file. This will not work because it needs all the other files like "FastSerial.cpp" to run properly. So when you say you're doing it this way to insure you get the right files this does not make sense. If it compiles using <FastSerial.h> then you are getting the correct files. As to why the path "../mavlink/include/mavlink.h" works...this is because of the way mavlink is built. I believe their documentation states this is the only file you need to include.
You should probably read a bit on the arduino website...here are a few links
http://www.arduino.cc/en/Hacking/Libraries
http://arduino.cc/en/Reference/Include
http://arduino.cc/en/Hacking/BuildProcess
Let me know if this helps

**Comment by Coreduino** [comment]
@alaney Thanks so much for helping me crack the "undefined reference to" problem I had.
My library had .C files and not .CPP - renaming them fixed my compiler issues. :o)

**Comment by alaney** [comment]
no problem
